; 2022/10/19/수 첫 작성
; 2022/10/20/목  + 3 시프트 3 : 노션의 바로가기 입력과 충돌


::kkk::김대희


#ESC::run notepad


; -------------------------------------------
;  자동 완성
; -------------------------------------------




; -------------------------------------------
;  단축키(핫키) 정의  Function
; -------------------------------------------
F1::     	;
;F2::     	;
F3::     	;
F4::     	;
F5::     	;
F6::     	;
F7::     	;
F8::     	;
F9::     	;
F10::     	;
F11::     	;
F12::     	;


; -------------------------------------------
;  단축키(핫키) 정의  ctrl
; -------------------------------------------
^1:: /    	;
^2::     	;
^3::     	;
^4::     	;
^5::     	;
^6::     	;
^7::     	;
^8::     	;
^9::     	;
^0::     	;
^r::Reload     ; 스크립트 다시 로드(핫키 Ctrl+r)

; -------------------------------------------
;  단축키(핫키) 정의  alt
; -------------------------------------------
!1::     	;
!2::     	;
!3::     	;
!4::     	;
!5::     	;
!6::     	;
!7::     	;
!8::     	;
!9::     	;
!0::     	;

; -------------------------------------------
;  단축키(핫키) 정의  shift (+)
; -------------------------------------------
;+1::     	;
;+2::     	;
;+3::     	;
;+4::     	;
;+5::     	;
;+6::     	;
;+7::     	;
;+8::     	;
;+9::     	;
;+0::     	;

; -------------------------------------------
;  단축키(핫키) 정의  window
; -------------------------------------------
#1::     	;
#2::     	;
#3::     	;
#4::     	;
#5::     	;
#6::     	;
#7::     	;
#8::     	;
#9::     	;
#0::     	;
#n::run notepad ; 노트패드
		return	; 종료선언

#v::run "C:\Program Files\Microsoft VS Code\Code.exe" ;비주얼
		return	; 종료선언

#m::run Code ;비주얼
		return	; 종료선언

;#s::run C:\Users\user\AppData\Local\SourceTree\SourceTree.exe	; 소스트리 실행
;		return ;종료선언

;금일 업무
#a::run, chrome.exe "https://www.notion.so/Today-5d17c1bb00a548fe8853abac55c579b3"
#b::run, chrome.exe "https://www.notion.so/bacbeb09e064493aa7fed844b6691e47" ; 도서관
#c::run, chrome.exe "https://www.notion.so/bacbeb09e064493aa7fed844b6691e47" ; 도서관

#s::run, chrome.exe "https://www.notion.so/c414eef18a1b401c80fa957ea5aa8888" ; 바로가기

;#e::run, chrome.exe "https://www.notion.so/keyboard-shortcuts-8a08c009fddc4142997b663625e97d90" ; 단축키
#r::run, chrome.exe "https://www.notion.so/keyboard-shortcuts-8a08c009fddc4142997b663625e97d90" ; 단축키


#f::run, chrome.exe "www.naver.com"
#h::run, chrome.exe "https://www.notion.so/AutoHotKey-AHK-826171ca23e24cf097efd5e6fb22e6d9"
#j::run, chrome.exe "https://www.notion.so/cc316468e3fb44559a0d636c31984e12" ; 공부
#l::run, chrome.exe "https://www.notion.so/bacbeb09e064493aa7fed844b6691e47" ; 도서관


#p::run, chrome.exe "https://www.notion.so/dba33baacaee478e852b34460baa6c21" ; 포교사

#q::run, chrome.exe "https://www.notion.so/LaTeX-4e696da5d7e746279550ebc7b7650be2" ; 암기장


